### ISSUE TITLE
circular dependency on util.inherits

### ISSUE THREAD

**Issue by tjmonsi** [defunctzombie/node-util#10]
Hi, 

I am having problems with using multiparty, which uses fd-slicer, which then uses util.inherits. I was looking as to why util.inherits became null. I looked at the code and saw that util.inherits require the inherits package. I looked at the inherits package, and it exports the util.inherits value. 

I was wondering what happened? why the circular dependency?

**Comment by kevinkace** [comment]
Running into the same issue.

**Comment by mcclure** [comment]
Likewise, this is currently blocking me from using this module in a non-Node v8 embed.

**Comment by mcclure** [comment]
This is currently blocking me from using this module with a non-Node v8 embed. If I hand-modify my package-lock.json so that inherits 2.0.3 is used instead of inherits 2.0.1, the problem goes away and the module works. If you accept either of the outstanding "Allow inherits dependency to be latest compatible" pull requests I believe this will solve the problem.

**Comment by bukuta** [comment]
The `util` from `npm` is still using `inherits@2.0.1`. 
Does the author consider to publish a new package from this repository?

**Comment by goto-bus-stop** [comment]
@defunctzombie could i get access to the npm package? i'd like to do a release for the above (and for `util.promisify` soon after)

**Comment by goto-bus-stop** [comment]
`goto-bus-stop` there too. Thanks!

On 3 June 2018 18:14:22 CEST, Roman Shtylman <notifications@github.com> wrote:
>@goto-bus-stop What is your npm username?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/defunctzombie/node-util/issues/10#issuecomment-394172910

-- 
Sent from mobile. Please excuse my brevity.

**Comment by defunctzombie** [comment]
@goto-bus-stop done

**Comment by goto-bus-stop** [comment]
fixed in 0.10.4. thanks!
