### ISSUE TITLE
Transfer ownership to an Org

### ISSUE THREAD

**Issue by wmhilton** [defunctzombie/node-util#22]
@defunctzombie You are in the envious position of having a super popular module with a long history. But it doesn't look like you have been able to keep this project properly maintained. The npm module hasn't been updated in 4 years, and this module no longer has all the same features that the core "util" module provides. As @CMCDragonkai [points out](https://github.com/defunctzombie/node-util/pull/21#issuecomment-343665403), forking is undesirable because the fork would no longer have the coveted "util" package name on npm. Many of us would love to see some of the outstanding issues closed and PRs merged. Would it be possible to transfer stewardship from your personal Github account to a group org, as well as transfer the npm package ownership to a group? I know both @mikeal and @sindresorhus - who contributed to the [promisify PR](https://github.com/defunctzombie/node-util/pull/21) are well established member in the node.js community and would be responsible co-maintainers. I'm obviously lesser known but have co-maintained `tree-kill` which is also downloaded a lot and was in a similar situation two years ago when I offered to co-maintain it. I don't have a strong opinion about what org `util` should belong to (browserify? a new one?) or who the members are, I just would like it to be owned and maintained by the community so we can start merging some of the outstanding PRs.

**Comment by defunctzombie** [comment]
@mikeal @sindresorhus do you want to take over maintaining?

I would also be happy with this module moving to the node.js organization.

**Comment by defunctzombie** [comment]
> I don't have a strong opinion about what org util should belong to (browserify? a new one?)

It should not belong to browserify.

**Comment by wmhilton** [comment]
> I would also be happy with this module moving to the node.js organization.

You mean [https://github.com/nodejs](https://github.com/nodejs)? That actually makes the most sense to me as well.

**Comment by CMCDragonkai** [comment]
A simple solution is to also add extra maintainers.

**Comment by defunctzombie** [comment]
Waiting for a response from the two names I referenced above; if you want to ping them about this.

**Comment by wmhilton** [comment]
I just pinged 'em. 🎺

**Comment by goto-bus-stop** [comment]
Hey, I'd be happy to help maintain this too, as I'm fairly active in the browserify space these days.

**Comment by defunctzombie** [comment]
@goto-bus-stop great! I have added you as a collaborator. I'll still gate the NPM publish until I've seen a few of the changes land and then can add you there as well! Just ping me as needed.

**Comment by defunctzombie** [comment]
I am going to consider this issue closed for now.
