### ISSUE TITLE
Module not found: Error: Can't resolve './support/isBuffer'

### ISSUE THREAD

**Issue by JonathanWilbur** [defunctzombie/node-util#30]
I get this error:

```
ERROR in ./node_modules/util/util.js
Module not found: Error: Can't resolve './support/isBuffer' in '<REDACTED>'
 @ ./node_modules/util/util.js 526:19-48
 @ ./node_modules/asn1-ts/dist/node/asn1.js
 @ ./source/AuthenticationFramework/index.ts
 @ ./source/index.ts
 @ multi ./source/index.ts
```

I believe this package is required by TypeScript. My code does not use it directly.

This is on a MacBook Air, whose output of `uname -a` yields this output:

```
Darwin <REDACTED> 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

The fix is for me to open the package add `.js` to the end of the `./support/isBuffer` in this line:

https://github.com/defunctzombie/node-util/blob/cfbf5d0acf112759a8aa7c2339a1694c52cf82d6/util.js#L536

NPM Version: `6.5.0`
Node Version: `v11.1.0`

**Comment by goto-bus-stop** [comment]
The .js should be added automatically by bundlers. Are you using a custom `extensions: []` configuration with webpack?

**Comment by JonathanWilbur** [comment]
@goto-bus-stop Wow! You nailed it! That was the problem. Sorry for the trouble. I will close this issue.
