### ISSUE TITLE
At Sveltekit project process is not defined in util.js

### ISSUE THREAD

**Issue by Cainuriel** [defunctzombie/node-util#81]
![image](https://github.com/browserify/node-util/assets/37802572/cf3474e6-6b38-462c-87ce-b8cd82363c08)

my pachage.json:

```
	"devDependencies": {
		"@playwright/test": "^1.30.0",
		"@sveltejs/adapter-auto": "^1.0.2",
		"@sveltejs/adapter-netlify": "^1.0.0-next.88",
		"@sveltejs/kit": "^1.3.10",
		"@typescript-eslint/eslint-plugin": "^5.50.0",
		"@typescript-eslint/parser": "^5.50.0",
		"eslint": "^8.33.0",
		"eslint-config-prettier": "^8.6.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"prettier": "^2.8.3",
		"prettier-plugin-svelte": "^2.9.0",
		"prisma": "^4.14.1",
		"rome": "^11.0.0",
		"svelte": "^3.55.1",
		"svelte-check": "^3.0.3",
		"tslib": "^2.5.0",
		"typescript": "^4.9.5",
		"vite": "^4.1.1",
		"vitest": "^0.25.8"
	},
	"type": "module",
	"dependencies": {
		"@lucia-auth/adapter-prisma": "^2.0.0",
		"@picocss/pico": "^1.5.7",
		"@prisma/client": "^4.9.0",
		"lucia-auth": "^1.7.0",
		"svelte-select": "^5.7.0",
		"xrpl": "^2.11.0"
	}
```
When the server is up, this error appears. I have to say that it has appeared suddenly. The project has not had any problems until now. The only thing I did was to use process.env.VARIABLE in a script[ when it was not the valid way](https://joyofcode.xyz/sveltekit-environment-variables). When I removed this usage, this error appeared, which is already a node error. 
I cleared the cache and it doesn't work either.

**Comment by ljharb** [comment]
Sounds like a bug in sveltekit then - this package (like most on npm) is a node module, and node globals like `process` are expected to be there, and bundlers are thus supposed to provide them.

I'd suggest filing an issue on SvelteKit; while they may not support node modules by default, I'm sure there's a config option or plugin that will make it work.

**Comment by Cainuriel** [comment]
https://github.com/browserify/node-util/issues/81#issuecomment-1714185618
You are absolutely right. I am in the wrong place. 
Thank you for your help.
